name: test and build
on:
  push:
    branches: [ builds ]
jobs:
  build_linux:
    runs-on: ubuntu-20.04
    env:
      os-name: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: python ./build.py test.test
      - run: python ./build.py armor.build-linux
  build_macosx:
    runs-on: macos-11
    env:
      os-name: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: brew install create-dmg
      - run: python ./build.py test.test
      - run: python ./build.py armor.build-osx
  build_windows:
    runs-on: ${{ matrix.os }}
    env:
      os-name: ${{ matrix.os }}
      KIVY_GL_BACKEND: 'angle_sdl2'
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: python ./build.py armor.build-windows
