name: build docker
on:
  push:
    branches: [ build_docker ]
jobs:
  build_docker:
    runs-on: ubuntu-20.04
    env:
      os-name: ubuntu-20.04
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: python ./build.py test.test
      - run: python ./build.py armor.build-linux --no-do-upload
      - run: python ./build.py armor.build-docker