name: test and build
on:
  push:
    branches: [ build ]
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
jobs:
  build_linux:
    runs-on: ubuntu-20.04
    env:
      os-name: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: python ./build.py test.test
      - run: python ./build.py armor.build-linux
  build_windows:
    runs-on: ${{ matrix.os }}
    env:
      os-name: ${{ matrix.os }}
      KIVY_GL_BACKEND: 'angle_sdl2'
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          # windows build no longer working for some reason.
          # try disabling pip caching
          # cache: 'pip'
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: python ./build.py armor.build-windows
