name: customer macos-11 build
on:
  create:
jobs:
  build_macosx:
    if: ${{ startsWith(github.ref, 'refs/tags/customer_build_macos-11_') }}
    runs-on: macos-11
    env:
      os-name: macos-11
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
      RSA_PUB: ${{ secrets.RSA_PUB }}
      RSA_PRIV: ${{ secrets.RSA_PRIV }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: brew install create-dmg
      - run: python ./build.py test.test
      - name: build the app
        env:
          TAG: ${{ steps.vars.outputs.tag }}
        run: |
          python ./build.py armor.build-osx
