name: docs
on:
  push:
    branches: [ docs ]
jobs:
  build_linux:
    runs-on: ubuntu-20.04
    env:
      os-name: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: sudo apt-get install pandoc -y
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: python ./build.py documentation.dockerfile
      - run: python ./build.py documentation.build-cli-docs
      - run: python ./build.py documentation.build
      - run: python ./build.py documentation.upload